name: flet_admob_pro
description: Native and rewarded AdMob controls for AI Master Pro.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  google_mobile_ads: ^8.0.0
  flet:
    path: ../../../../../../../packages/flet
